version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    networks:
      - my-network
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

  web:
    build: .
    container_name: django_app
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 3 notesapp.wsgi:application"
    networks:
      - my-network
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    volumes:
      - .:/app
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:1.21-alpine
    container_name: nginx_server
    networks:
      - my-network
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    depends_on:
      - web
    restart: unless-stopped

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
  static_volume: